### PR TITLE
Update README.md

### LINKED ISSUE #3: new issue
dfdfdfdfdfdf df dfd fdfdf
dfdf dfdfdf

### PR DESCRIPTION
**Pull request by saulogtis**
dsdsdfsdf
sdf
sf
sd
f
```ts
const o = 0;
```

### CODE REVIEW

**Comment by saulogtis** [comment]
Comment

**Comment by saulogtis** [comment]
> Comment

hshshshshsh

**Comment by saulogtis** [comment]
sdfsfsdf

**Comment by saulogt** [comment]
sssss

**Comment by saulogt** [comment]
ssss

**Comment by saulogt** [comment]
sssss

**Comment by saulogt** [comment]
gfhfghfgh

**Comment by saulogtis** [comment]
uhliuhjo

**Pull request closed without merging**
